### ISSUE TITLE
allow merging with dx8->dx9 converter

### ISSUE THREAD

**Issue by phly95** [massanoori/THRotator#1]
there should be another dll that is d3d9.dll designed for games running with the enbconverter, because of the windows 10 issues

**Comment by massanoori** [comment]
Although I've experienced some problems with enbconverter, I would like to know the issues on your environment since some issues have been fixed since Windows 10 Anniversary Update according to http://wikiwiki.jp/thtools/?THRotator (Japanese site). It says:

> You don't have to use an extra tool to fix fullscreen issues if you have updated to Windows 10 Anniversary Update (1607). But it is recommended to use DX8 to DX9 Converter for Touhou 6 since there are still issues.

I've tested THRotator 1.2.2 with enbconverter by copying d3d9.dll of THRotator 1.2.2 instead of d3d8.dll.
The results are:

* Environment:
  * Windows 10 Pro 1703 15063.483 x64
  * GeForce GTX 960
  * 12 GB RAM
  * Intel Core i7-4790 3.60 GHz
* On Touhou 6, 8, and 9.5, d3d9.dll of THRotator 1.2.2 works fine with enbconverter.
* On Touhou 7 in fullscreen mode,  d3d9.dll of THRotator 1.2.2 works fine as well.
* On Touhou 7 in windowed mode,  d3d9.dll of THRotator 1.2.2 can rotate a screen. But Touhou 7 doesn't accept player's inputs after THRotator's window is opened.

Do the results and issues above match yours?

**Comment by massanoori** [comment]
The issue mentioned in the previous comment has been fixed in [v1.3.0](https://github.com/massanoori/THRotator/releases/tag/v1.3.0).
THRotator now works with DX8 to DX9 converter.

I've also updated the installation manual for those who install DX8 to DX9 converter.
You can install THRotator with the converter by following the instructions given in <https://massanoori.github.io/THRotator/en/pages/install.html>.
